version: '2'
 
services:
 web:
   restart: always
   build: ./web
   expose:
     - "5000"
   volumes:
     - /usr/src/app/web/static
   environment:
      PYTHONPATH: ./
   command: gunicorn -w 1 --threads 8 -k gthread -b :8000 restapi:app
 
 nginx:
   restart: always
   build: ./nginx
   ports:
     - "5000:80"
   volumes:
     - /www/static
   volumes_from:
     - web
   depends_on:
     - web
   links:
   - web